site_name: LegiÃ£o Wiki
site_url: https://imexplo.github.io/Legiao-Wiki/
site_description: DocumentaÃ§Ã£o oficial e guia de otimizaÃ§Ã£o do Modpack LegiÃ£o.
site_author: EXPLO

# Tema
theme:
  name: material
  language: pt-BR
  logo: assets/assets/logo-legiao-minimum.png  # (Lembre de colocar a imagem da cobra aqui!)
  favicon: assets/favicon.png
  
  # Cores
  palette:
    # Modo Escuro
    - scheme: slate
      primary: red      # O 'L' Vermelho
      accent: green     # A Cobra Verde (botÃµes, links)
      toggle:
        icon: material/weather-night
        name: Mudar para modo claro
    # Modo Claro -> Pra quem Ã© lelÃ© da cabeÃ§a
    - scheme: default
      primary: red
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Mudar para modo escuro

  # Extras
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

  nav:
  - ğŸ  InÃ­cio: index.md
  - ğŸ‡ºğŸ‡¸ English: en/index.md
  
  - ğŸš€ InstalaÃ§Ã£o: instalacao.md
  - âš¡ OtimizaÃ§Ã£o (DH): otimizacao.md
  - ğŸ› ï¸ Ajuda & FAQ: faq.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg